### ISSUE TITLE
build.author can't work

### ISSUE THREAD

**Issue by bensq2** [lizheming/drone-wechat#6]
hi， I will upgrade drone from 0.8 to 1, but I found everything is well execpt {{build.author}}.
{{repo.name}} 
{{build.number}}
{{build.branch}}
all works ok
could you check it, thx!

**Comment by lizheming** [comment]
I used `{{build.author}}` just few hours ago,  and it's ok for me. `{{build.author}}` will replaced with enviroment `DRONE_COMMIT_AUTHOR` https://github.com/lizheming/drone-render/blob/master/src/render.js#L27, so you can add a step to echo `DRONE_COMMIT_AUTHOR` to debug it.

```
- name: author-debug
  image: alpine
  commands:
    - echo $DRONE_COMMIT_AUTHOR
```
